main: me.lewisainsworth.vanguardclans.VanguardClan
version: 1.5.5
name: VanguardClans
author: Lewis_Ainsworth
api-version: "1.20"
softdepend: [Vault, PlaceholderAPI, TAB]

commands:
  clan:
    description: Comandos principales de los clanes.
  clanadmin:
    description: Administra el plugin VanguardClans.
  scstats:
    description: Muestra estadísticas del jugador.

permissions:
  vanguardclans.admin:
    description: Acceso a comandos administrativos.
    default: op

  # Permisos específicos para comandos/clanes
  vanguardclans.user.create:
    description: Permiso para crear un clan.
    default: false

  vanguardclans.user.sethome:
    description: Permiso para ir a la home.
    default: false

  vanguardclans.user.delhome:
    description: Permiso para borrar la home del clan.
    default: false

  vanguardclans.user.home:
    description: Permiso para home.
    default: false

  vanguardclans.bypass.homecooldown:
    default: op

  vanguardclans.bypass.homedelay:
    default: op

  vanguardclans.bypass.nametag:
    description: Allows seeing hidden nametags (privacy bypass)
    default: op
  vanguardclans.admin.nametagreset:
    description: Permite usar /clanadmin nametagreset
    default: op

  vanguardclans.user.list:
    description: Permiso para listar clanes.
    default: false

  vanguardclans.user.join:
    description: Permiso para unirse a un clan.
    default: false

  vanguardclans.user.leave:
    description: Permiso para salir de un clan.
    default: false

  vanguardclans.user.disband:
    description: Permiso para disolver un clan.
    default: false

  vanguardclans.user.kick:
    description: Permiso para expulsar a un miembro de un clan.
    default: false

  vanguardclans.user.ally:
    description: Permiso para gestionar alianzas.
    default: false

  vanguardclans.user.ff:
    description: Permiso para configurar fuego amigo.
    default: false

  vanguardclans.user.chat:
    description: Permiso para usar chat de clan.
    default: false

  vanguardclans.user.stats:
    description: Permiso para ver estadísticas de clanes.
    default: false

  vanguardclans.user.invite:
    description: Permiso para invitar jugadores a un clan.
    default: false

  vanguardclans.user.economy:
    description: Permiso para depositar o retirar dinero del banco del clan.
    default: false

  vanguardclans.user.slots:
    description: Permiso para ver y mejorar los slots del clan.
    default: false

  vanguardclans.user.top:
    description: Permiso para ver el ranking de clanes.
    default: false

  vanguardclans.user.rank:
    description: Permiso para gestionar rangos del clan.
    default: false

  vanguardclans.user.accept:
    description: Permiso para aceptar invitaciones a clanes.
    default: false

  vanguardclans.user.decline:
    description: Permiso para rechazar invitaciones a clanes.
    default: false

  vanguardclans.user.resign:
    description: Permiso para renunciar a un clan.
    default: false

  vanguardclans.user.report:
    description: Permiso para reportar clanes.
    default: false
